version: '2'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
    command: 'npm run dev'

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
